class AddSeedDataToCustomers < ActiveRecord::Migration
  def migrate(direction)
    super
    if direction == :up then
      CompanyProfile.where(:companyable_type => 'Customer').delete_all
      User.where(:companyable_type => 'Customer').delete_all
      Customer.delete_all
	  Customer.create!(:name=>'niming', :c_id=> 5, :company_profile_attributes => { :company_name => '上海匿名有限公司', :company_addr=>'上海市浦东新区世纪大道123号', :postcode=>'210000', :distribution_list=>'niming@niming.com,lgq@niming.com', :contact=>'倪名', :primary_phone=>'021-58986524'}, :users_attributes => {'0'=>{:email=>'niming@example.com', :password=>'niming-pwd', :password_confirmation=>'niming-pwd'}})
	  Customer.create!(:name=>'zqc', :c_id=> 6, :company_profile_attributes => { :company_name => '中企创科技', :company_addr=>'广东省河源市高新技术开发区兴业大道科7路冠瑞工业园', :postcode=>'222333', :distribution_list=>'guoying@primemobi.com,zhaojianwei@primemobi.com,duanzheng@primemobi.com,qiandonghong@primemobi.com', :contact=>'明慧泉', :primary_phone=>'15915448805'}, :users_attributes => {'0'=>{:email=>'zqc@example.com', :password=>'876897', :password_confirmation=>'876897'}})
	  Customer.create!(:name=>'ruyi', :c_id=> 7, :company_profile_attributes => { :company_name => '陕西如意有限公司', :company_addr=>'陕西省咸阳市秦都区咸兴路7号', :postcode=>'600233', :distribution_list=>'caijie@jinyutuo.com', :contact=>'蒋宋超', :primary_phone=>'15829489603'}, :users_attributes => {'0'=>{:email=>'ruyi@example.com', :password=>'237684', :password_confirmation=>'237684'}})
	  Customer.create!(:name=>'aijing', :c_id=> 8, :company_profile_attributes => { :company_name => '深圳埃晶科技', :company_addr=>'深圳市龙华镇南贤商业广场A座607室', :postcode=>'392333', :distribution_list=>'gonghui@aijingkj.com,jiangli@aijingkj.com', :contact=>'龚辉', :primary_phone=>'13823286858'}, :users_attributes => {'0'=>{:email=>'aijing@example.com', :password=>'873642', :password_confirmation=>'873642'}})
	  Customer.create!(:name=>'taifeng', :c_id=> 10, :company_profile_attributes => { :company_name => '深圳泰丰网络有限公司', :company_addr=>'深圳市南山区南海大道新能源大厦A座3楼', :postcode=>'', :distribution_list=>'qin0036@126.com', :contact=>'黄辉峰', :primary_phone=>'13828813765'}, :users_attributes => {'0'=>{:email=>'taifeng@example.com', :password=>'123456', :password_confirmation=>'123456'}})
	  Customer.create!(:name=>'kaer', :c_id=> 11, :company_profile_attributes => { :company_name => '威海卡尔电气', :company_addr=>'山东威海高新区大连路58号', :postcode=>'256427', :distribution_list=>'13156311417@126.com,niuyj@kaer.cn', :contact=>'于军静', :primary_phone=>'13156311417'}, :users_attributes => {'0'=>{:email=>'kaer@example.com', :password=>'123456', :password_confirmation=>'123456'}})
	  Customer.create!(:name=>'nttx', :c_id=> 12, :company_profile_attributes => { :company_name => '深圳钮泰通讯', :company_addr=>'上海浦东新区亮秀路112号Y1座608室', :postcode=>'201000', :distribution_list=>'liaohaixia@airm2m.com,beautiful.lq@163.com', :contact=>'廖海霞', :primary_phone=>'15026502458'}, :users_attributes => {'0'=>{:email=>'nttx@example.com', :password=>'000000', :password_confirmation=>'000000'}})
	  Customer.create!(:name=>'wujie', :c_id=> 13, :company_profile_attributes => { :company_name => '深圳吴杰科技', :company_addr=>'深圳市宝安区72区扬田路马边大厦812室 ', :postcode=>'', :distribution_list=>'tiapc@163.com', :contact=>'吴杰', :primary_phone=>'15338808377'}, :users_attributes => {'0'=>{:email=>'wujie@example.com', :password=>'123456', :password_confirmation=>'123456'}})
	  Customer.create!(:name=>'botai', :c_id=> 14, :company_profile_attributes => { :company_name => '惠州市博泰通讯设备有限公司', :company_addr=>'惠州市惠澳大道惠南高新科技产业园金钟路19号A1栋', :postcode=>'', :distribution_list=>'lianghq@pro-tel.com.cn,huiqing.liang@163.com', :contact=>'梁惠清', :primary_phone=>'13502275192'}, :users_attributes => {'0'=>{:email=>'botai@example.com', :password=>'654321', :password_confirmation=>'654321'}})
	  Customer.create!(:name=>'gaoxunbaling', :c_id=> 15, :company_profile_attributes => { :company_name => '深圳高讯霸灵', :company_addr=>'深圳市龙岗区宝龙工业城宝龙六路新中桥工业园A栋西2楼', :postcode=>'', :distribution_list=>'qin0036@126.com', :contact=>'杨奎', :primary_phone=>'13682503053'}, :users_attributes => {'0'=>{:email=>'gaoxunbaling@example.com', :password=>'123456', :password_confirmation=>'123456'}})
	  Customer.create!(:name=>'jinyutuo', :c_id=> 16, :company_profile_attributes => { :company_name => '深圳市金裕拓科技有限公司', :company_addr=>'深圳市福田区车公庙都市阳光名苑2栋6D室   ', :postcode=>'', :distribution_list=>'caijie@jinyutuo.com', :contact=>'蔡颉', :primary_phone=>'13903027016'}, :users_attributes => {'0'=>{:email=>'jinyutuo@example.com', :password=>'123456', :password_confirmation=>'123456'}})
	  Customer.create!(:name=>'henghetongxin', :c_id=> 17, :company_profile_attributes => { :company_name => '上海恒河通信科技有限公司', :company_addr=>'深圳市宝安区石岩镇爱群路同富裕工业区1-6栋4楼（正耀科技） ', :postcode=>'', :distribution_list=>'zyfan@tdhiway.com,smtech@163.com', :contact=>'胡林', :primary_phone=>'15999622766'}, :users_attributes => {'0'=>{:email=>'henghetongxin@example.com', :password=>'123456', :password_confirmation=>'123456'}})
	  Customer.create!(:name=>'luxutech', :c_id=> 18, :company_profile_attributes => { :company_name => '深圳鲁旭科技', :company_addr=>'深圳市宝安区107国道490号A栋3楼 ', :postcode=>'', :distribution_list=>'adusun@126.com', :contact=>'杜立建', :primary_phone=>'13760120227'}, :users_attributes => {'0'=>{:email=>'luxutech@example.com', :password=>'123456', :password_confirmation=>'123456'}})
	  Customer.create!(:name=>'qihao', :c_id=> 19, :company_profile_attributes => { :company_name => '奇豪数码科技有限公司', :company_addr=>'上海闵行区浦江镇新骏环路189号A栋2楼203', :postcode=>'', :distribution_list=>'zhuliqun@airm2m.com', :contact=>'焦刚', :primary_phone=>'13764424166'}, :users_attributes => {'0'=>{:email=>'qihao@example.com', :password=>'654321', :password_confirmation=>'654321'}})
	  Customer.create!(:name=>'cqak', :c_id=> 23, :company_profile_attributes => { :company_name => '重庆艾科基业科技有限公司', :company_addr=>'重庆市南岸区玉马路8号 中国物联网科技孵化楼5楼', :postcode=>'', :distribution_list=>'liaohaixia@airm2m.com', :contact=>'涂兴华 ', :primary_phone=>'13667604290'}, :users_attributes => {'0'=>{:email=>'cqak@example.com', :password=>'654321', :password_confirmation=>'654321'}})
	  Customer.create!(:name=>'qddz', :c_id=> 24, :company_profile_attributes => { :company_name => '广州市启大电子科技有限公司 ', :company_addr=>'广州市天河区珠吉街东环路3号广桥工业园B栋3楼', :postcode=>'210200', :distribution_list=>'zhuliqun@airm2m.com', :contact=>'侯云茂', :primary_phone=>'18688448811'}, :users_attributes => {'0'=>{:email=>'qddz@example.com', :password=>'654321', :password_confirmation=>'654321'}})
	  Customer.create!(:name=>'BDHH', :c_id=> 25, :company_profile_attributes => { :company_name => '北京博电华恒通迅技术有限公司', :company_addr=>'北京市丰台区六里桥南里华源一里十六号楼1O9', :postcode=>'201000', :distribution_list=>'zhuliqun@airm2m.com', :contact=>'王洪超', :primary_phone=>'13901370133'}, :users_attributes => {'0'=>{:email=>'BDHH@example.com', :password=>'654321', :password_confirmation=>'654321'}})
	  Customer.create!(:name=>'yipangkeji', :c_id=> 26, :company_profile_attributes => { :company_name => '深圳市益庞电子', :company_addr=>'深圳市龙华大浪街道办华荣路联建科技工业园4栋3楼', :postcode=>'111111', :distribution_list=>'qin0036@126.com', :contact=>'林总', :primary_phone=>'15338720999'}, :users_attributes => {'0'=>{:email=>'yipangkeji@example.com', :password=>'123456', :password_confirmation=>'123456'}})
	  Customer.create!(:name=>'sikerui', :c_id=> 27, :company_profile_attributes => { :company_name => '深圳市思科瑞电子有限公司', :company_addr=>'深圳市宝安区航城大道 兆丰工业园A栋6楼 ', :postcode=>'200000', :distribution_list=>'gonghui@aijingkj.com', :contact=>'韦小姐  ', :primary_phone=>'15220151015'}, :users_attributes => {'0'=>{:email=>'sikerui@example.com', :password=>'654321', :password_confirmation=>'654321'}})
	  Customer.create!(:name=>'ruiheng', :c_id=> 9, :company_profile_attributes => { :company_name => '福州瑞恒科技有限公司', :company_addr=>'福建省厦门市湖里区殿前一路536号望龙工业大厦3楼', :postcode=>'', :distribution_list=>'13860603267@139.com,15980706198@139.com,13489194982@139.com,xtdyqg@163.com,15980558710@139.com,15711538489@139.com,18259150579@139.com,13960010720@139.com,shenxl.y@163.com,wangweilongcom@163.com', :contact=>'谢运昌', :primary_phone=>'15711538489'}, :users_attributes => {'0'=>{:email=>'ruiheng@example.com', :password=>'234983', :password_confirmation=>'234983'}})
	  Customer.create!(:name=>'syzhongxun', :c_id=> 20, :company_profile_attributes => { :company_name => ' 江苏中讯数码电子有限公司', :company_addr=>'宜兴市丁蜀镇汤蜀路中段南侧', :postcode=>'', :distribution_list=>'229699363@qq.com', :contact=>'王欢', :primary_phone=>'13606153969'}, :users_attributes => {'0'=>{:email=>'syzhongxun@example.com', :password=>'123456', :password_confirmation=>'123456'}})
	  Customer.create!(:name=>'jichang', :c_id=> 22, :company_profile_attributes => { :company_name => '深圳集昌科技有限公司', :company_addr=>'深圳市宝安区福永镇怀德翠湖工业园1栋3F', :postcode=>'', :distribution_list=>'gonghui@aijingkj.com', :contact=>'李君昌', :primary_phone=>'15920084555'}, :users_attributes => {'0'=>{:email=>'jichang@example.com', :password=>'123456', :password_confirmation=>'123456'}})
    end
  end		  
end


